version: '3.7'

networks:
  openproject-frontend:
  openproject-backend:

volumes:
  pgdata:
  opdata:

x-op-restart-policy: &restart_policy
  restart: unless-stopped
x-op-image: &image
  image: openproject/community:${TAG:-11}
x-op-app: &app
  <<: *image
  <<: *restart_policy
  hostname: '192.168.2.100'
  container_name: 'openproject'
  environment:
    RAILS_CACHE_STORE: 'memcache'
    OPENPROJECT_CACHE__MEMCACHE__SERVER: 'cache:11211'
    OPENPROJECT_RAILS__RELATIVE__URL__ROOT: '${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-/openproject}'
    DATABASE_URL: '${DATABASE_URL}'
    # DATABASE_URL: 'postgres://postgres:p4ssw0rd@db/openproject'
    USE_PUMA: 'true'
    # set to true to enable the email receiving feature. See ./docker/cron for more options
    IMAP_ENABLED: '${IMAP_ENABLED:-false}'
  volumes:
    - '${OPENPROJECT_HOME}/opdata:/var/openproject/assets'
    - '/etc/localtime:/etc/localtime:ro'

services:
  db:
    image: postgres:10
    <<: *restart_policy
    stop_grace_period: '3s'
    volumes:
      - '${OPENPROJECT_HOME}/pgdata:/var/lib/postgresql/data'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    networks:
      - openproject-backend

  cache:
    image: memcached
    <<: *restart_policy
    networks:
      - openproject-backend

  proxy:
    <<: *image
    <<: *restart_policy
    command: './docker/prod/proxy'
    ports:
      - '${PORT:-8080}:80'
    environment:
      APP_HOST: web
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: '${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-/openproject}'
    depends_on:
      - web
    networks:
      - openproject-frontend

  web:
    <<: *app
    command: './docker/prod/web'
    networks:
      - openproject-frontend
      - openproject-backend
    depends_on:
      - db
      - cache
      - seeder

  worker:
    <<: *app
    command: './docker/prod/worker'
    networks:
      - openproject-backend
    depends_on:
      - db
      - cache
      - seeder

  cron:
    <<: *app
    command: './docker/prod/cron'
    networks:
      - openproject-backend
    depends_on:
      - db
      - cache
      - seeder

  seeder:
    <<: *app
    command: './docker/prod/seeder'
    restart: on-failure
    networks:
      - openproject-backend
# secrets:
#   postgres_db:
#     file: ./secrets/postgres_db.txt # put postgresql db name to this file
#   postgres_password:
#     file: ./secrets/postgres_password.txt # put postgresql password to this file
#   postgres_user:
#     file: ./secrets/postgres_user.txt # put postgresql username to this file
